// Mocks generated by Mockito 5.1.0 from annotations
// in poke_dex/test/stores/pokemon/pokemon_store_v2_store_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:poke_dex/features/data/models/pokemon_detail_model.dart' as _i2;
import 'package:poke_dex/features/data/models/specie.dart' as _i3;
import 'package:poke_dex/mock/repositories/pokemon_v2_repository_mock.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakePokemonDetailModel_0 extends _i1.Fake
    implements _i2.PokemonDetailModel {}

class _FakeSpecieModel_1 extends _i1.Fake implements _i3.SpecieModel {}

/// A class which mocks [PokemonV2RepositoryMock].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokemonV2RepositoryMock extends _i1.Mock
    implements _i4.PokemonV2RepositoryMock {
  MockPokemonV2RepositoryMock() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.PokemonDetailModel> fetchPokemonDetails(String? name) =>
      (super.noSuchMethod(Invocation.method(#fetchPokemonDetails, [name]),
              returnValue: Future<_i2.PokemonDetailModel>.value(
                  _FakePokemonDetailModel_0()))
          as _i5.Future<_i2.PokemonDetailModel>);
  @override
  _i5.Future<_i3.SpecieModel> fetchSpecie(String? number) =>
      (super.noSuchMethod(Invocation.method(#fetchSpecie, [number]),
              returnValue: Future<_i3.SpecieModel>.value(_FakeSpecieModel_1()))
          as _i5.Future<_i3.SpecieModel>);
}
